[theme]

# Primary accent for interactive elements
primaryColor = '#01807e'

# Background color for the main content area
backgroundColor = '#263846'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#666666'

# Color used for almost all text
textColor = '#FFFFFF'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace)
# Default: "sans serif"
font = "sans serif"

#Brand palette
##100e0d
##01807e
##666666
##ffffff
##263846